### ISSUE TITLE
About ComputeLaneCount arguments

### ISSUE THREAD

**Issue by Piker-Alpha** [vit9696/Lilu#15]
I don't know where else to put this for IntelGraphicsFixup.kext, and I don't know if you already know this (since you used unk1 as name) but the second argument to ComputeLaneCount() is: IODetailedTimingInformationV2 *timingInfo

**Comment by vit9696** [comment]
Hi, looks like I forgot to run c++filt(h) on the symbol =) More important, might you have an idea what unk3 is actually? I got a feeling it has some relation to connector type but did not go deep enough.

**Comment by Piker-Alpha** [comment]
Not from the top of my head, but I think to have something much better for you. Look at this:
```
AppleIntelFramebuffer::validateDetailedTiming(IOFBDisplayModeDescription modeInfo, unsigned long long sizeOf_modeInfo)
```
Now search for this code snippet in the binary:
```
00000000000173db         call       AppleIntelFramebuffer::maxSupportedDepths(IODetailedTimingInformationV2 const*)
00000000000173e0         dec        eax
00000000000173e2         mov        dword [r13+0xc], eax
```
That stuffs the value into this structure:
``` 
struct IODisplayModeInformation {
    UInt32                      nominalWidth;	// index 0
    UInt32                      nominalHeight;	// index 4
    IOFixed1616                 refreshRate;	// index 8
    IOIndex                     maxDepthIndex;	// index 12/0xC <==
    UInt32                      flags;
    UInt16			imageWidth;
    UInt16			imageHeight;
    UInt32                      reserved[ 3 ];
};
typedef struct IODisplayModeInformation IODisplayModeInformation;
```
Another code snippet:
```
00000000000173e6         mov        eax, dword [r13+0x44]	// IOAppleTimingID
00000000000173ea         test       eax, eax	// if (IOAppleTimingID == kIOTimingIDInvalid) {}
00000000000173ec         je         loc_1740e
```
Here the AppleTimingID is checked. Now you know what structures to look at ;)

**Comment by vit9696** [comment]
Thanks =), it is a good hint, although I was more or less aware of it at the time of the research.
Basically [this](https://ghostbin.com/paste/mh69v) and [this](https://ghostbin.com/paste/3s6ya) are the relevant parts. Unk3 is something about bandwidth as well, but it is still not very clear to me.

Yet even if we know what this name is all about, we will not be able to properly fix the issue. For some weird reason (well, I guess the reason is that Apple never uses this GPU with connectors) `this->availableLaneCount` is 0 for HD 530. As a result the kext thinks it cannot add any more screens. Figuring the cause of it will be a more proper solution, but it is not that simple, and just pretending to require 0 lanes works fine as well.

I guess I will close this issue, maybe somebody sees this one day and comes up with an idea =)

**Comment by Piker-Alpha** [comment]
So you know what this 3 is?
```
if ( *(_DWORD *)(*(_QWORD *)&this->field_15096 + 40LL) != 3 )
```

**Comment by vit9696** [comment]
Yes, that is connector type. 3 is LVDS, and the check means whether the connection is external. I have it written somewhere, if I remember correctly I identified DP and HDMI too.

**Comment by vit9696** [comment]
Found the notes, HDMI — 1, DisplayPort — 2, LVDS — 3 if that helps :)

**Comment by Piker-Alpha** [comment]
Really? Isn't that kIOScreenLockLocked?

**Comment by vit9696** [comment]
Hmm, I don't have an idb with the tests already to backup my thoughts, but your theory sounds worth thinking about. Do you have more details on why it could lock state?

**Comment by Piker-Alpha** [comment]
I can't remember it. What I do remember is that I checked the validateXxX routines. You could add them in the plugin and see what it returns. Example. validateDisplayMode is an interesting one.

What do we need for this to be called from within the plugin? Sorry. I don't have tools handy here right now...

Note: unk3 can be 6, 10, 12 or 20 and then the lane count is: 4, 2, 2 and 1 (for 1920 * 1200).

**Comment by vit9696** [comment]
Yes, unk3 is assigned in AppleIntelFramebufferController::GetDPCDInfo (DisplayPortConfigurationData). And is basically a pure result of the AUX command:
```C
uint8_t outaux[4];
AppleIntelFramebufferController::ReadAUX(
             this,
             (AppleIntelFramebuffer *)framebuffer,
             0,
             0x10u,
             outaux,
             displayPath);
  *((uint8_t *)framebuffer + 0x22EC) = outaux[0];
  *((uint8_t *)framebuffer + 0x22ED) = outaux[0] & 0xF;
  *((uint8_t *)framebuffer + 0x22EE) = outaux[0] >> 4;
  if ( outaux[1] == 6 )
  {
    framebuffer->unk3 = 6;
  }
  else if ( outaux[1] == 10 )
  {
    framebuffer->unk3 = 10;
  }
  else
  {
    if ( outaux[1] != 20 )
    {
      framebuffer->unk3 = 6;
      return 0xE00002C7;
    }
    if ( *(_BYTE *)(*(_QWORD *)&this->gap1E0[5080] + 96LL) < 0 )
    {
      framebuffer->unk3 = 10;
    }
    else
    {
      framebuffer->unk3 = 20;
    }
  }
framebuffer->availableLaneCount = outaux[2] & 0x1F;
  if ( (outaux[2] & 0x1F) != 1 )
  {
    if ( framebuffer->availableLaneCount != 2 )
    {
      if ( framebuffer->availableLaneCount != 4 )
      {
        return 0xE00002C7LL;
      }
    }
  }
```
I am rather unaware of DP spec, but
unk3 = 6 → pixelspace = 162000000
unk3 = 10 → pixelspace = 270000000
unk3 = 12 → pixelspace = 324000000
unk3 = 20 → pixelspace = 540000000 
This corresponds to the 6th slide of [this presentation](http://www.vesa.org/wp-content/uploads/2010/12/DisplayPort-DevCon-Presentation-DP-1.2-Dec-2010-rev-2b.pdf). pixelspace is basically bandwidth per frame. The latter formula comes from [this manual](https://www.x.org/docs/intel/HD/IHD_OS_Vol_3_Part4_BJS.pdf), page 69. But it has nothing useful for bits 15:8 used for unk3 :D

Given that in our cards unk3 is 0, I would give a try to debugging AppleIntelFramebufferController::ReadAUX commands and see what is returned for that 0x10 if anything. But if I remember correctly, patching unk3 to any of the values different from only 0 caused various panics.

As usual I am pretty short on time, and I also don't have the hardware. If you want to debug this, AppleIntelFramebufferController::GetDPCDInfo and AppleIntelFramebufferController::ReadAUX are the first things to try. To route them through the plugin simply use the routeFunction available in kern_patcher.hpp, it will generate the trampoline for you.

By the way, we could use a more convenient way of communication than github, iMessage for example. Feel free to mail me at vit9696 dog avp dot su.

**Comment by Piker-Alpha** [comment]
On now I remember it again. Thanks for pointing this out. You know what. I looked at GetDPCDInfo() and setDPPowerState() earlier. For the wake issues after sleep. Well. What I remember is that the latter returns 0xe00002bc so that is why it won't set framebuffer->availableLaneCount and never initialises unk3. The reason for this is that It return much earlier. If you make it jump over that section, then it it should work.

**Note**: We also have 0x1e and thus the maximum bandwidth has increased.

p.s. We're on holidays, on a sailboat and we only have e-mail.

**Comment by vit9696** [comment]
> I looked at GetDPCDInfo() and setDPPowerState() earlier. For the wake issues after sleep. Well. What I remember is that the latter returns 0xe00002bc so that is why it won't set framebuffer->availableLaneCount and never initialises unk3. The reason for this is that It returns much earlier. If you make it jump over that section, then it it should work.

Not really. I asked a friend to try returning 0 from setDPPowerState when it is called from GetDPCDInfo, and that only resulted in a hang when booting. The same thing happens when setDPPowerState always returns 0. I am afraid it won't work this way, and the overall picture is more complex.

P.S. Enjoy your sojourn ^^, as for disasm it is IDA indeed.

**Comment by Piker-Alpha** [comment]
Your friend must be doing something wrong as I am not running into a hang here on a SKL based computer with HS DP-3.

Could you please ask your friend to add some lines to the IGFX plugin and return zero from there? I bet that the hang is gone when I see his code.

Thanks!

**Comment by vit9696** [comment]
Well, the code is mine. While I am not totally confident in it, working on a lot of other things at the moment, I don't see anything wrong here: [src1](https://ghostbin.com/paste/ty7tu), [src2](https://ghostbin.com/paste/3h48a). And yes, he is also using HS DP3 with HD 530.

**Comment by vit9696** [comment]
Ok, I fixed a minor typo and asked for a retest, it did not change anything.

**Comment by Piker-Alpha** [comment]
You mean like he is still experiencing the same kind of hang? In that case. Remove the call to the original function and return 0 there. Nothing more. This tells me that the arguments don't match with the original function.

The next step is to solve the problem where getDPCDInfo returns 0xe00002d6.

**Comment by vit9696** [comment]
The arguments do match:
```
$ c++filt __ZN31AppleIntelFramebufferController15SetDPPowerStateEP21AppleIntelFramebufferhP21AppleIntelDisplayPath
AppleIntelFramebufferController::SetDPPowerState(AppleIntelFramebuffer*, unsigned char, AppleIntelDisplayPath*)
$ c++filt __ZN31AppleIntelFramebufferController11GetDPCDInfoEP21AppleIntelFramebufferP21AppleIntelDisplayPath
AppleIntelFramebufferController::GetDPCDInfo(AppleIntelFramebuffer*, AppleIntelDisplayPath*)
```
The first invisible one is `this` aka `void *` obviously. I think the cause of the hang is not the routed function but the fact some other commands run after we return 0.  
To confirm this I reverted return code changes and a panic, to get exactly the same behaviour the original kext offered but proxying getDPCDInfo and setDPPowerState, and he booted with no issues.

As for another test I changed setDPPowerState to always return 0 and not call to the original func just as you suggested, and he got the same freeze at IOConsoleUser.
However, after he force-rebooted after getting this hang he got my added "STILL NULL LANE COUNT" panic log, even though the panic itself was not seen at the hang time (and he does not use no reboot after panic).

This made me think that even though I patched setDPPowerState, lane count may sometimes be 0 still. So the panic has always happened but never displayed onscreen.
Afterwards I simply disabled the panic but left the lane count patch. He got a successful boot, so his hang was caused by my added panic. I checked the log, and indeed it was full of "igfx @ reporting worked lane count" messages, meaning that patching setDPPowerState is not enough. 

To recheck this I disabled the panic and removed the lane count patch. He got a usual hang.

**Comment by Piker-Alpha** [comment]
Ok. Understood. Good work so far. One important question; Is your friend using a DP monitor or some other (HDMI/DVI) monitor? Please note that the call to SetDPPowerState should only be done for DP monitors. Other monitors should skip it.

**Comment by vit9696** [comment]
It is HDMI, and his MB actually has no DP. From what I know DP ports work just fine and they do not need any patches, but they are rare.
I also had a thought that the function should not be called for HDMI screens, but it seems to be done to my surprise. Perhaps a failure in this case is actually an expected return code.

**Comment by Piker-Alpha** [comment]
Yup. I didn't need it with my other board, which had a DP port on it. But it's not expected result. Take a look at getDisplayStatus which calls IsHPDLow If you add these two, to the plugin, then your friend and I can see what it does. It should not call setDPPowerState from it.

**Comment by vit9696** [comment]
Well, to be honest, I am busy with other stuff at the moment. It might be a good idea to continue Intel research, in both black screen area and pavp issues, but I previously stopped not because I could not make it further, but because I am reasonably short on time, and there are more important things.

I would appreciate if you could make some tests on your own for the time being. After all you understand things pretty clearly. Or perhaps we could return to this together some while later (perhaps after your journey).

**Comment by Piker-Alpha** [comment]
No problem. Done. 

computeLaneCount now returns 6 for unk3 and 1 as return value. Which is good. 

Could you please link a complete IDA dump so that I can debug things further, since I do not have Windows installed and I did not expect to need IDA on my holiday.

**Comment by vit9696** [comment]
Do you mean hex-rays dump or ids? If you are fine with PikeRAlpha at yahoo dot com, I could send both there.

**Comment by Piker-Alpha** [comment]
Yes please.

**Comment by vit9696** [comment]
Sure, sent.

**Comment by Piker-Alpha** [comment]
Thanks. Got it. Anyway. As I said earlier; if you jump over it it should work. It didn't for you friend, but this what I did to get it to work:
```
  if ( *((_DWORD *)displayPath + 10) == 2
    || (++qword_17FA30, *((_DWORD *)displayPath + 10) == 3)
    && (++qword_17FA38, *(_BYTE *)(*(_QWORD *)&this->gap1E0[5080] + 96LL) & 0x40) )
  {
    ++qword_17FA28;
    result = AppleIntelFramebufferController::SetDPPowerState(
               this,
               (AppleIntelFramebuffer *)framebuffer,
               1u,
               displayPath);
    if ( result )
    {
      ++qword_17FA40;
      return result;
    }
  }
  result = AppleIntelFramebufferController::ReadAUX(
             this,
             (AppleIntelFramebuffer *)framebuffer,
             0,
             0x10u,
             outaux,
             displayPath);
  if ( result )
  {
    ++qword_17FA48;
    return result;
  }
```
If I change that 1u in the call to SetDPPowerState into 3u and put a filter on the powerState, we get something like this:
```
uint32_t IGFX::setDPPowerState(void *framebufferController, void *framebuffer, uint8_t powerState, void *displayPath)
{
	uint32_t retValue = 0;

	if (callbackIgfx && callbackIgfx->orgSetDPPowerState)
	{
		retValue = callbackIgfx->orgSetDPPowerState(framebufferController, framebuffer, powerState, displayPath);
		printf("igfx : setDPPowerState(%d) retValue = 0x%x", powerState, retValue);
	}

	if (powerState == 3)
	{
		retValue = 0;
	}

	return retValue;
}
```
Then we get by the error that SetDPPowerState returns. The next step was to add another filter. This time for the call to ReadAUX:
```
uint32_t IGFX::readAUX(void * framebufferController, void * AppleIntelFramebuffer, unsigned int unk2, unsigned short unk3, void * out_buffer, void * AppleIntelDisplayPath)
{
	uint32_t retValue = 0;

	if (callbackIgfx && callbackIgfx->orgReadAUX)
	{
		retValue = callbackIgfx->orgReadAUX(framebufferController, AppleIntelFramebuffer, unk2, unk3, &out_buffer, AppleIntelDisplayPath);
		printf("igfx : readAUX retValue = 0x%x, unk2 = 0x%x, unk3 = 0x%x\n", retValue, unk2, unk3);
	}
	
	if (unk2 == 0x0 && unk3 == 0x10)
	{
		retValue = 0;
	}
	return retValue;
}
```
This is how I get by the error that ReadAUX returns, but to make it all work I also need this:
```
uint32_t IGFX::validateDetailedTiming(void * AppleIntelFramebuffer, IOFBDisplayModeDescription * displayModeDescr, unsigned long long sizeOfdisplayModeDescr)
{
	uint32_t retValue = 0;
	
	if (callbackIgfx && callbackIgfx->orgValidateDetailedTiming)
	{
		retValue = callbackIgfx->orgValidateDetailedTiming(AppleIntelFramebuffer, displayModeDescr, sizeOfdisplayModeDescr);
		
		if (displayModeDescr->timingInfo.detailedInfo.v2.horizontalActive == 1920 && displayModeDescr->timingInfo.detailedInfo.v2.verticalActive == 1200)
		{
			retValue = 0;
		}
		
		printf("igfx : validateDetailedTiming retValue = 0x%x, sizeOfTimingInfo = 0x%llx\n", retValue, sizeOfdisplayModeDescr);
	}
	
	return retValue;
}
```
Yet another filter. This time on the resolution that I want. Now. The crux of the problem appears to be related to the DisplayPath data. This has to be confirmed by someone else. You can add a few lines to dump the data.

The next thing that we need is someone with DP monitor so that this person can make a dump of the DisplayPort data for us. If that looks right, then we can patch our broken data.

**Comment by vit9696** [comment]
Huh… that's quite something.
Let me try to keep up.

Argument change from 1u to 3u for SetDPPowerState. You simply use it to track the right call from AppleIntelFramebufferController::GetDPCDInfo, right? That's because I cannot find any calls with 3, and I don't really understand what 3 does. For this reason I would rather not risk passing random arguments and wrap GetDPCDInfo with some flag probably. Since we cannot have two IGPUs and it is all single-threaded, it should be safer and cleaner.

Then you had to add this AUX thing, so it is confirmed that it also fails, which is quite annoying. And to compensate for invalid DisplayPath data returned by this AUX read you simply forced a zero from validateDetailedTiming.

As for valid DisplayPath data, I tried asking the people I know whether they might have a board with a display port. But so far nothing, maybe you could try something on the blog? After all there is a slight chance one with straight hands could read it and at least dump the data for us…

But to be honest, even if we have this data, what will we do with it without properly AppleIntelDisplayPath structure and meaning. What I see it is a parent of AppleIntelHDCP, but as for the rest is pretty opaque:

```C
struct AppleIntelDisplayPath {
  AppleIntelDisplayPathVT *vt;
  void *unk1;
  HDCP1CLASS *HDCP1CLASS;
  void *unk2;
  void *unk3;
  uint32_t displayType;
  uint8_t pad1[1065];
  uint8_t flags;
  uint8_t pad2[2];
  uint32_t displayPipe;
  uint32_t pad3[44];
  void *someHDCPclass;
  void *unk4;
};
```
Need a lot more time to find all the other fields, and I think most are outside of this kext. That's how I read things now in validateDetailedTiming:
```C
  if ( this->field_9834 )
  {
    ++perfCounter21;
    ++perfCounter22;
    v16 = &this->displayPath;
    if ( this->displayPath->displayType != 3 )
    {
      ++perfCounter23;
      lane_count = 0;
      if ( !AppleIntelFramebufferController::ComputeLaneCount(
              this->self,
              &displayModeDescr->timingInfo.detailedInfo.v2,
              this->bpp,
              this->unk3,
              &lane_count)
        || (++perfCounter24, lane_count > (unsigned int)this->availableLaneCount) )
      {
        ++perfCounter25;                        // kIOReturnUnsupported
        return 0xE00002C7;
      }
    }
  }
```
To be honest, I still think it just some kind of a displayType, not anything else. I remember attempting to change the value somewhere, but it either panic'ed or did not work. But now that we know the place, could you try passing 2 instead of 3 for ReadUAX and maybe SetDPPowerState? Perhaps they could give us valid out_buffer?..

To be honest, all in all, now I am starting to wonder whether we are going in the right direction. In fact, should `this->field_9834` even be 1. There are only two places for it becoming one, and it is straight-dependent on AAPL,DisplayPipe. One place is `AppleIntelFramebufferController::start`, another place is `AppleIntelFramebufferController::setBootPipe`.

In start it looks like this:
```C
        displayPath = v98->displayPath;
        AppleIntelFramebufferController::MapFBToPort(
          v81,
          (AppleIntelFramebuffer *)v98,
          v98->displayPath,
          displayPath->pad1[1060]);
        v159 = (signed int *)&displayPath->displayPipe;
        v98->vt->__ZN15IORegistryEntry11setPropertyEPKcPvj(
          (IORegistryEntry *)v98,
          "AAPL,DisplayPipe",
          &displayPath->displayPipe,
          4u);
        if ( *((_BYTE *)v81 + 5598) == 1 )
        {
          ++qword_185EA0;
          *(_DWORD *)val = 0;
          v98->vt->__ZN15IORegistryEntry11setPropertyEPKcPvj((IORegistryEntry *)v98, "AAPL,DisplayPipe", val, 4u);
          v100 = &v98->field_9834;
          v98->field_9834 = 1;
        }
        else
        {
          v100 = &v98->field_9834;
        }
```

Just some annoying 5598 (15DEh) says, we go with 1. This comes from `AppleIntelFramebufferController::getOSInformation`. TL;DR it is the 18th byte of gPlatformInformationList entry:
```asm
__text:000000000002A8FA  movzx   eax, byte ptr [rdx+18] ; rdx points to gPlatformInformationList entry
__text:000000000002A8FE  mov     [rbx+2420h], al
__text:000000000002A904  mov     [rbx+15DEh], al
```
This has something to do with the connectors, right? I think you know more than me at this point :) Would you like to hear your thoughts.

**Comment by Piker-Alpha** [comment]
Yes. The 1 -> 3 change was done to track that specific call to SetDPPowerState. BTW; 3 is sleep so that's not an issue. And this check:
```
if ( *((_BYTE *)v81 + 5598) == 1 )
```
That is only true for platform data with a single frame buffer (there's currently only one of it). A simple  shortcut to set property AAPL,boot-display earlier.

Here's the result of changing the value of displayType:
0 -> hang
1  -> Ok, without call to SetDPPowerState(3)
2 -> Ok, with call to SetDPPowerState(3)
3 -> black screen
4 -> black screen

I also checked your struct AppleIntelDisplayPath and changed it into:
```
struct IOAppleIntelDisplayPath
{
	AppleIntelDisplayPathVT *vt;
	void *			unk1;
	HDCP1CLASS *	HDCP1CLASS;
	void *			unk2;
	void *			unk3;

	uint32_t		displayType;

	uint8_t			pad0[12];	// 0x10 0x41 0x06 0x00 0x00 0x41 0x06 0x00 0x00 0x00 0x00 0x00
								// 0x10 0x42 0x06 0x00 0x00 0x42 0x06 0x00 0x00 0x00 0x00 0x00
								// 0x10 0x43 0x06 0x00 0x00 0x43 0x06 0x00 0x00 0x00 0x00 0x00

	uint8_t			portMask;	// 0 -> port-number = 0
								// 4 -> port-number = 6
								// 5 -> port-number = 5
								// 6 -> port-number = 7
	uint8_t			pipeMask;
	uint8_t			displayOnline;
	
	uint8_t			pad1[1];	// ?

	uint32_t		avSignalType;

	uint8_t			displayEDID[1024];
	uint16_t		displayProductID;
	uint32_t		displaySerialNumber;
	uint8_t			diaplayManufactureWeek;
	uint8_t			diaplayManufactureYear;
	uint8_t			displayVersionEDID;
	uint8_t			displayRevisionEDID;

	uint8_t			pad2[1];	// ?

	uint32_t		connectorType;

	uint8_t			pad3[1];	// ?

	uint32_t		framebufferNumber;
	uint32_t		displayFlags;
	uint32_t		displayPipe;

	// [ 0] = 0x00000780 0x000004b0 0x00000000 0x00000000 0x00000780 0x000004b0 0x00000000 0x00000000
	// [ 8] = 0x00000000 0x9e507000 0xffffff81 0x00000002 0x00000000 0x00000000 0x00000000 0x261cb400
	// [16] = 0xffffff80 0x00000000 0x00000000 0x261cb200 0xffffff80 0x00000000 0x00000000 0x00000000
	// [24] = 0x00000000 0x00000000 0x00000000 0x00007400 0x8a000012 0x33ff3333 0x3333c09c 0x01000000
	// [32] = 0x0dff3333 0x00002dde 0xffffff80 0x217f6c00 0xffffff80 0xdeadbeef 0xdeadbeef 0x80e18848
	// [40] = 0xffffff7f 0x00060007 0x00000000 0x2181ad20 0xffffff80 0x2184da80 0xffffff80 0x2184da40

	uint32_t		horizontalActive;
	uint32_t		verticalActive;

	uint32_t		pad4[2];	// ?

	uint32_t		horizontalScaled;
	uint32_t		verticalScaled;

	uint32_t		pad5[40];	// ?

	void *			someHDCPclass;
	void *			unk4;
};
```
But here is something interesting. I switched on my computer this morning and booted. Then I checked the log and there was not a single call to SetDPPowerState and no errors for calls to ReadAUX. Also less calls.

Shutting down and re-booting is not the same so I have to shut it down – which I have to do anyway – and see what I get tonight.

**Comment by vit9696** [comment]
As for the logs it unfortunately likely is a Sierra+ feature. For some godforsaken reason it may accidentally drop a chunk of logs close to graphics acceleration start. So probably the logs were there, just they were eaten by the daemon.

As for displayType tests they look somewhat logical, except 3. But I think I got exactly the same behaviour in the past when I tried to go with 3. So probably it is "ok" to some level.

Very good job with IOAppleIntelDisplayPath (y), I guess that is quite something if we find a person capable of dumping DP info.

As for field_9834, in this case it is the other method, setBootPipe. I applied your new type definition, and explored the function a little more. It sets field_9834 to 1 if connectorType is 0, 1, 2, 3. I.e. pretty much for any connection, including HDMI.

All in all this confirms that field_9834 is not a culprit (well, at least it was designed to be 1 for HDMI), but the other two possibilities remain:
- the original idea: broken display path data for hdmi some reason
- a possibility of an incorrect check (`if ( this->displayPath->displayType != 3 )`), e.g. they could have meant `displayType == 3` or even `displayType != 3 && displayType != 1`

**Comment by Piker-Alpha** [comment]
Yup. Data is back; log show still sucks.

connectorType is 0, 1, 2, 3? Well. That really has to be framebufferNumber. Let me check. Yeah. Wrong structure. Here's a working one:
```
struct IOAppleIntelDisplayPath
{
	AppleIntelDisplayPathVT *	vt;
	void *			unk1;
	HDCP1CLASS *	HDCP1CLASS;
	void *			unk2;
	void *			unk3;

	uint32_t		displayType;

	uint8_t			pad0[12];	// 0x10 0x41 0x06 0x00 0x00 0x41 0x06 0x00 0x00 0x00 0x00 0x00
								// 0x10 0x42 0x06 0x00 0x00 0x42 0x06 0x00 0x00 0x00 0x00 0x00
								// 0x10 0x43 0x06 0x00 0x00 0x43 0x06 0x00 0x00 0x00 0x00 0x00

	uint8_t			portMask;	// 0 -> port-number = 0
								// 4 -> port-number = 6
								// 5 -> port-number = 5
								// 6 -> port-number = 7
	uint8_t			pipeMask;
	uint8_t			displayOnline;
	
	uint8_t			pad1[1];	// 0x00

	uint32_t		avSignalType;

	uint8_t			displayEDID[1024];
	uint16_t		displayProductID;
	
	uint8_t			displaySerialNumber[4];
	
	uint8_t			displayManufactureWeek;
	uint8_t			displayManufactureYear;
	uint8_t			displayVersionEDID;
	uint8_t			displayRevisionEDID;
	
	uint32_t		connectorType;
	uint32_t		framebufferNumber;
	uint32_t		displayFlags;
	uint32_t		displayPipe;
	
	uint32_t		pad2[2];	// 0x00000000 0x00000000
	
	uint32_t		horizontalActive;
	uint32_t		verticalActive;
	
	uint32_t		pad3[2];	// 0x00000000 0x00000000
	
	uint32_t		horizontalScaled;
	uint32_t		verticalScaled;
	
	uint32_t		pad4[40];	// ?
	
	void *			someHDCPclass;
	void *			unk4;
};
typedef struct IOAppleIntelDisplayPath IOAppleIntelDisplayPath;
```
All additions are now showing the expected data. Sorry for that. But anyway. That still means that basically all type of connections set field_9834.

**Comment by vit9696** [comment]
> connectorType is 0, 1, 2, 3? Well. That really has to be framebufferNumber.

Aha, makes sense. Thanks for fixing.

> That still means that basically all type of connections set field_9834.

Yes. I guess this is good to know at least. Could we eliminate the possibility of a mistake left by some Apple dev by changing `this->displayPath->displayType != 3` to `this->displayPath->displayType != 2`? I tried finding an older kext for a proof, failed unfortunately, but I certainly remember that there was no such check before 10.12.5b2. If it works… eh, maybe try filing a radar on that and mailing somebody from AAPL's team?

DP data comparison would be useful, but let's be serious, what could really go wrong here so that a small change in lane count computation fixes the output. I would expect more drastic failures if anything was badly broken.

pad0 looks strange to my eyes, feels like an array of 4 ints, and with this positioning it may describe some connection hardware?

**Comment by Piker-Alpha** [comment]
2 doesn't work here. Not with DVI and also not with HDMI. What does work for me is binary patch method:
```
0000000000017b49	48 83 bf 68 31 00 00 00 cmpq	$0x0, 0x3168(%rdi) // Check 1
0000000000017b51	74 75 			je	0x17bc8

0000000000017b53	48 ff 05 7e 9a 08 00 	incq	0x89a7e(%rip)
0000000000017b5a	83 7d d0 00 		cmpl	$0x0, -0x30(%rbp) // Check 2
0000000000017b5e	75 68 			jne	0x17bc8

0000000000017b60	48 ff 05 69 9a 08 00 	incq	0x89a69(%rip)
0000000000017b67	48 ff 05 32 90 08 00 	incq	0x89032(%rip)
0000000000017b6e	49 8b 87 90 3b 00 00 	movq	0x3b90(%r15), %rax
0000000000017b75	83 78 28 03 		cmpl	$0x3, 0x28(%rax) // Check 3
0000000000017b79	74 4d 			je	0x17bc8

0000000000017b7b	48 ff 05 46 9a 08 00 	incq	0x89a46(%rip)
0000000000017b82	4c 8d 45 d4 		leaq	-0x2c(%rbp), %r8
0000000000017b86	41 c7 00 00 00 00 00 	movl	$0x0, (%r8)
0000000000017b8d	41 8b 97 20 27 00 00 	movl	0x2720(%r15), %edx
0000000000017b94	41 0f b6 8f 7f 23 00 00 movzbl	0x237f(%r15), %ecx
0000000000017b9c	4c 89 e6 		movq	%r12, %rsi
0000000000017b9f	e8 60 96 02 00 		callq	__ZN31AppleIntelFramebufferController16ComputeLaneCountEPK29IODetailedTimingInformationV2jjPj ## AppleIntelFramebufferController::ComputeLaneCount(IODetailedTimingInformationV2 const*, unsigned int, unsigned int, unsigned int*)
0000000000017ba4	84 c0 			testb	%al, %al
0000000000017ba6	90 			nop
0000000000017ba7	90 			nop

0000000000017ba8	48 ff 05 39 9a 08 00 	incq	0x89a39(%rip)
0000000000017baf	41 0f b6 87 81 23 00 00 movzbl	0x2381(%r15), %eax
0000000000017bb7	90 			nop
0000000000017bb8	90 			nop
0000000000017bb9	90 			nop
0000000000017bba	75 0c 			jne	0x17bc8

0000000000017bbc	48 ff 05 1d 9a 08 00 	incq	0x89a1d(%rip)
0000000000017bc3	e9 c9 01 00 00 		jmp	0x17d91

0000000000017bc8	48 8b 05 d1 8f 08 00 	movq	0x88fd1(%rip), %rax
0000000000017bcf	48 8d 48 01 		leaq	0x1(%rax), %rcx
0000000000017bd3	48 89 0d c6 8f 08 00 	movq	%rcx, 0x88fc6(%rip)
0000000000017bda	49 8b 8f 90 3b 00 00 	movq	0x3b90(%r15), %rcx
0000000000017be1	83 79 28 01 		cmpl	$0x1, 0x28(%rcx)
0000000000017be5	75 72 			jne	0x17c59
```
Not that we want to use this. Also. Note that there are _three_ checks. The third one is not a great one, we now know, but what do you think about the first check? Isn't that the AGDC state (I was told to look at the AGDC code)?

The IOAppleIntelDisplayPath struct is interesting, and it would be nice to know exactly what it does/is used for, but the problem is more likely related to AGDC code.

I happen to still have the 10.12.5b1 kext. Just in case you are interested ;)

Sure. pad0 may be wrong. We just don't know yet. That's why I left it like that.

**Comment by vit9696** [comment]
> 2 doesn't work here. Not with DVI and also not with HDMI. What does work for me is binary patch method

Ugh, I basically made a mess of my own words:
> Found the notes, HDMI — 1, DisplayPort — 2, LVDS — 3 if that helps :)

Should be 1 of course to avoid HDMI failing.

As for three checks, sorry, I have a slightly different asm, and I don't see another check here O_o:
```asm
__text:000000000001841B 4C 8D 63 2C                          lea     r12, [rbx+2Ch]
__text:000000000001841F 41 80 BF 6A 26 00 00+                cmp     byte ptr [r15+266Ah], 0
__text:0000000000018427 74 7F                                jz      short loc_184A8 ; first check, this is field_9834
__text:0000000000018429 48 FF 05 28 A2 16 00                 inc     cs:perfCounter21
__text:0000000000018430 48 FF 05 19 98 16 00                 inc     cs:perfCounter22
__text:0000000000018437 4D 8D AF F8 3A 00 00                 lea     r13, [r15+3AF8h]
__text:000000000001843E 49 8B 87 F8 3A 00 00                 mov     rax, [r15+3AF8h]
__text:0000000000018445 83 78 28 03                          cmp     dword ptr [rax+28h], 3
__text:0000000000018449 74 64                                jz      short loc_184AF ;second check, this is display type
__text:000000000001844B 48 FF 05 FE A1 16 00                 inc     cs:perfCounter23
__text:0000000000018452 C7 85 40 FF FF FF 00+                mov     [rbp+lane_count], 0
__text:000000000001845C 49 8B BF D0 01 00 00                 mov     rdi, [r15+1D0h] ; controller
__text:0000000000018463 41 8B 97 88 26 00 00                 mov     edx, [r15+2688h] ; bpp
__text:000000000001846A 41 0F B6 8F EF 22 00+                movzx   ecx, byte ptr [r15+22EFh] ; unk3
__text:0000000000018472 4C 8D 85 40 FF FF FF                 lea     r8, [rbp+lane_count] ; lane_count
__text:0000000000018479 4C 89 E6                             mov     rsi, r12        ; timingInfo
__text:000000000001847C E8 17 A9 02 00                       call    __ZN31AppleIntelFramebufferController16ComputeLaneCountEPK29IODetailedTimingInformationV2jjPj ; AppleIntelFramebufferController::ComputeLaneCount(IODetailedTimingInformationV2 const*,uint,uint,uint *)
__text:0000000000018481 84 C0                                test    al, al
__text:0000000000018483 74 17                                jz      short loc_1849C
__text:0000000000018485 48 FF 05 DC A1 16 00                 inc     cs:perfCounter24
__text:000000000001848C 41 0F B6 87 F1 22 00+                movzx   eax, byte ptr [r15+22F1h]
__text:0000000000018494 39 85 40 FF FF FF                    cmp     [rbp+lane_count], eax
__text:000000000001849A 76 13                                jbe     short loc_184AF
```

To my regret I don't remember where this AppleIntelSKLGraphicsFramebuffer comes from, but I think it was 10.12.5. The note says: `AppleSW  PROJECT:GraphicsDrivers  DEVELOPER:beretta  BUILT:Apr 22 2017 16:01:41`.

> I happen to still have the 10.12.5b1 kext. Just in case you are interested ;)

Yes, I am. And I found b3, by the way.
